### ISSUE TITLE
Needs JSON version now that MonoDevelop has switched formats

### ISSUE THREAD

**Issue by rmunn** [netpyoung/monodevelop-colors-tomorrow-theme#1]
At some point (apparently in MonoDevelop 4.0), MonoDevelop switched formats for color themes from XML to JSON. The new format is documented here:

http://www.monodevelop.com/developers/articles/color-scheme-definition/

This very nice theme is currently unable to be imported in modern versions of MonoDevelop (tested on version 5.9.6) until it's converted to a JSON format.

**Comment by netpyoung** [comment]
ahh, thanks to feedback. i will check that.

**Comment by netpyoung** [comment]
i added json version on https://github.com/netpyoung/monodevelop-colors-tomorrow-theme/tree/master/new_json
